apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PhaneendraReddyG/helm.git
    path: nginx-app    
    targetRevision: main
        
    helm:
      releaseName: nginx-app
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
        image:
          repository: httpd
          tag: "1.25.0"

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

