apiVersion: v1
entries:
  nginx-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-09T11:28:03.965572739Z"
    description: A Helm chart for Kubernetes
    digest: ffc66c01a9fb884af86f54786ba2948bd03b3736203bd2ba113b3dc708dc484d
    name: nginx-app
    type: application
    urls:
    - https://phaneendrareddy.github.io/helm/nginx-app-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-09T11:28:03.959953209Z"
